/*
 * File: app/store/Sensors.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArchitectApp.store.Sensors', {
    extend: 'Ext.data.Store',

    requires: [
        'ArchitectApp.model.Sensor'
    ],

    config: {
        data: [
            {
                name: 'File',
                description: 'Permette di scrivere o leggere un file nella memoria del dispositivo'
            },
            {
                name: 'Camera',
                description: 'Permette di catturare un\'immagine tramite la fotocamera o la galleria del dispositivo'
            },
            {
                name: 'Contacts',
                description: 'Permette di consultare e modificare la rubrica del dispositivo'
            },
            {
                name: 'Media',
                description: 'Permette di catturare o riprodurre file audio tramite il dispositivo'
            },
            {
                name: 'Geolocation',
                description: 'Permette di visualizzare la posizione corrente del dispositivo'
            },
            {
                name: 'Barcode',
                description: 'Permette di leggere un barcode tramite la fotocamera del dispositivo'
            },
            {
                name: 'Device',
                description: 'Permette di visualizzare le informazioni proprie del device'
            }
        ],
        model: 'ArchitectApp.model.Sensor',
        storeId: 'Sensors',
        sorters: {
            property: 'name'
        }
    }
});